/** Level 9 - Cycles (Insane) ~90 seconds
 *  The ultimate test: all mechanics combined, rapid mode switches, tight timing
 *  ~860 grid units */
export default {
  id: 9,
  name: 'Cycles',
  speed: 1.0,
  objects: [
    // === SECTION 1: Relentless opening (0-100) ===
    { type: 'spike', x: 5, y: 0 },
    { type: 'spike', x: 6, y: 0 },
    { type: 'spike', x: 7, y: 0 },
    { type: 'saw', x: 12, y: 1, radius: 1 },
    { type: 'spike', x: 18, y: 0 },
    { type: 'spike', x: 19, y: 0 },
    { type: 'orb', x: 22, y: 3, orbType: 'yellow_orb' },
    { type: 'spike', x: 24, y: 0 },
    { type: 'spike', x: 25, y: 0 },
    { type: 'spike', x: 26, y: 0 },
    { type: 'saw', x: 32, y: 2, radius: 1.5 },
    { type: 'spike', x: 40, y: 0 },
    { type: 'spike', x: 41, y: 0 },
    { type: 'orb', x: 44, y: 2, orbType: 'dash_orb' },
    { type: 'spike', x: 48, y: 0 },
    { type: 'spike', x: 49, y: 0 },
    { type: 'spike', x: 50, y: 0 },
    { type: 'pad', x: 56, y: 0, padType: 'pink_pad' },
    { type: 'spike', x: 62, y: 0 },
    { type: 'spike', x: 63, y: 0 },
    { type: 'spike', x: 64, y: 0 },
    { type: 'orb', x: 68, y: 3, orbType: 'pink_orb' },
    { type: 'spike', x: 70, y: 0 },
    { type: 'spike', x: 71, y: 0 },
    { type: 'spike', x: 72, y: 0 },
    { type: 'saw', x: 78, y: 1, radius: 1 },
    { type: 'slope', x: 84, y: 0, w: 2, h: 2, direction: 'up' },
    { type: 'platform', x: 86, y: 2, w: 2, h: 1 },
    { type: 'spike', x: 87, y: 3 },
    { type: 'slope', x: 88, y: 2, w: 2, h: 2, direction: 'down' },
    { type: 'spike', x: 94, y: 0 },
    { type: 'spike', x: 95, y: 0 },
    { type: 'spike', x: 96, y: 0 },

    // === SECTION 2: Speed ship + gravity (100-220) ===
    { type: 'checkpoint', x: 102, y: 0 },
    { type: 'color_trigger', x: 104, y: 0, colorType: 'purple', duration: 0.6 },
    { type: 'portal', x: 110, y: 0, portalType: 'speed_up' },
    { type: 'portal', x: 114, y: 0, portalType: 'ship' },
    { type: 'spike', x: 124, y: 0 },
    { type: 'spike', x: 124, y: 10, rot: 180 },
    { type: 'saw', x: 134, y: 6, radius: 1.5 },
    { type: 'spike', x: 142, y: 2 },
    { type: 'spike', x: 142, y: 8, rot: 180 },
    { type: 'portal', x: 150, y: 0, portalType: 'gravity' },
    // Ship inverted at speed
    { type: 'spike', x: 158, y: 0 },
    { type: 'spike', x: 158, y: 10, rot: 180 },
    { type: 'saw', x: 168, y: 4, radius: 1 },
    { type: 'spike', x: 176, y: 1 },
    { type: 'spike', x: 176, y: 9, rot: 180 },
    { type: 'portal', x: 184, y: 0, portalType: 'gravity' },
    { type: 'spike', x: 192, y: 0 },
    { type: 'spike', x: 192, y: 10, rot: 180 },
    { type: 'spike', x: 200, y: 2 },
    { type: 'spike', x: 200, y: 9, rot: 180 },
    { type: 'portal', x: 208, y: 0, portalType: 'cube' },
    { type: 'portal', x: 210, y: 0, portalType: 'speed_down' },

    // === SECTION 3: Rapid mode cycling (220-360) ===
    { type: 'checkpoint', x: 222, y: 0 },
    // Cube section
    { type: 'spike', x: 230, y: 0 },
    { type: 'spike', x: 231, y: 0 },
    { type: 'orb', x: 236, y: 3, orbType: 'yellow_orb' },
    { type: 'spike', x: 238, y: 0 },
    { type: 'spike', x: 239, y: 0 },
    // Wave
    { type: 'portal', x: 246, y: 0, portalType: 'wave' },
    { type: 'platform', x: 256, y: 4, w: 1, h: 8 },
    { type: 'platform', x: 264, y: 0, w: 1, h: 5 },
    { type: 'saw', x: 270, y: 7, radius: 1 },
    { type: 'platform', x: 276, y: 5, w: 1, h: 7 },
    // Ball
    { type: 'portal', x: 286, y: 0, portalType: 'ball' },
    { type: 'spike', x: 294, y: 0 },
    { type: 'platform', x: 298, y: 3, w: 4, h: 1 },
    { type: 'spike', x: 304, y: 0 },
    { type: 'spike', x: 308, y: 0 },
    { type: 'coin', x: 312, y: 5 },
    { type: 'platform', x: 316, y: 4, w: 4, h: 1 },
    { type: 'spike', x: 322, y: 0 },
    // Ship
    { type: 'portal', x: 328, y: 0, portalType: 'ship' },
    { type: 'spike', x: 336, y: 0 },
    { type: 'spike', x: 336, y: 10, rot: 180 },
    { type: 'saw', x: 344, y: 5, radius: 1 },
    // Cube
    { type: 'portal', x: 352, y: 0, portalType: 'cube' },

    // === SECTION 4: Slope + saw hell (360-470) ===
    { type: 'checkpoint', x: 362, y: 0 },
    { type: 'color_trigger', x: 364, y: 0, colorType: 'blue', duration: 0.6 },
    { type: 'slope', x: 372, y: 0, w: 3, h: 3, direction: 'up' },
    { type: 'platform', x: 375, y: 3, w: 3, h: 1 },
    { type: 'saw', x: 378, y: 5, radius: 1 },
    { type: 'slope', x: 378, y: 3, w: 3, h: 3, direction: 'down' },
    { type: 'spike', x: 384, y: 0 },
    { type: 'spike', x: 385, y: 0 },
    { type: 'saw', x: 390, y: 1, radius: 1 },
    { type: 'spike', x: 396, y: 0 },
    { type: 'spike', x: 397, y: 0 },
    { type: 'slope', x: 402, y: 0, w: 2, h: 2, direction: 'up' },
    { type: 'platform', x: 404, y: 2, w: 2, h: 1 },
    { type: 'saw', x: 408, y: 4, radius: 1 },
    { type: 'slope', x: 406, y: 2, w: 2, h: 2, direction: 'down' },
    { type: 'spike', x: 412, y: 0 },
    { type: 'spike', x: 413, y: 0 },
    { type: 'orb', x: 418, y: 3, orbType: 'yellow_orb' },
    { type: 'spike', x: 420, y: 0 },
    { type: 'spike', x: 421, y: 0 },
    { type: 'saw', x: 426, y: 2, radius: 1.5 },
    { type: 'spike', x: 434, y: 0 },
    { type: 'spike', x: 435, y: 0 },
    { type: 'spike', x: 436, y: 0 },
    { type: 'pad', x: 442, y: 0, padType: 'pink_pad' },
    { type: 'spike', x: 448, y: 0 },
    { type: 'spike', x: 449, y: 0 },
    { type: 'spike', x: 454, y: 0 },
    { type: 'spike', x: 455, y: 0 },
    { type: 'spike', x: 456, y: 0 },
    { type: 'spike', x: 462, y: 0 },
    { type: 'spike', x: 463, y: 0 },

    // === SECTION 5: Gravity madness (470-570) ===
    { type: 'checkpoint', x: 472, y: 0 },
    { type: 'spike', x: 480, y: 0 },
    { type: 'portal', x: 484, y: 0, portalType: 'gravity' },
    { type: 'spike', x: 490, y: 12, rot: 180 },
    { type: 'portal', x: 494, y: 0, portalType: 'gravity' },
    { type: 'spike', x: 500, y: 0 },
    { type: 'portal', x: 504, y: 0, portalType: 'gravity' },
    { type: 'spike', x: 510, y: 12, rot: 180 },
    { type: 'spike', x: 511, y: 12, rot: 180 },
    { type: 'portal', x: 516, y: 0, portalType: 'gravity' },
    { type: 'spike', x: 522, y: 0 },
    { type: 'spike', x: 523, y: 0 },
    { type: 'orb', x: 528, y: 3, orbType: 'blue_orb' },
    { type: 'spike', x: 530, y: 12, rot: 180 },
    { type: 'spike', x: 531, y: 12, rot: 180 },
    { type: 'orb', x: 536, y: 9, orbType: 'yellow_orb' },
    { type: 'spike', x: 538, y: 12, rot: 180 },
    { type: 'spike', x: 539, y: 12, rot: 180 },
    { type: 'spike', x: 540, y: 12, rot: 180 },
    { type: 'portal', x: 546, y: 0, portalType: 'gravity' },
    { type: 'saw', x: 552, y: 1, radius: 1 },
    { type: 'spike', x: 558, y: 0 },
    { type: 'spike', x: 559, y: 0 },
    { type: 'spike', x: 564, y: 0 },

    // === SECTION 6: Speed wave + saws (570-680) ===
    { type: 'checkpoint', x: 572, y: 0 },
    { type: 'color_trigger', x: 574, y: 0, colorType: 'magenta', duration: 0.6 },
    { type: 'portal', x: 580, y: 0, portalType: 'speed_up' },
    { type: 'portal', x: 584, y: 0, portalType: 'wave' },
    { type: 'platform', x: 594, y: 3, w: 1, h: 9 },
    { type: 'saw', x: 602, y: 2, radius: 1 },
    { type: 'platform', x: 608, y: 0, w: 1, h: 4 },
    { type: 'platform', x: 618, y: 5, w: 1, h: 7 },
    { type: 'saw', x: 626, y: 3, radius: 1 },
    { type: 'platform', x: 632, y: 0, w: 1, h: 5 },
    { type: 'coin', x: 638, y: 7 },
    { type: 'platform', x: 644, y: 4, w: 1, h: 8 },
    { type: 'saw', x: 652, y: 2, radius: 1 },
    { type: 'platform', x: 658, y: 0, w: 1, h: 5 },
    { type: 'platform', x: 668, y: 6, w: 1, h: 6 },
    { type: 'portal', x: 676, y: 0, portalType: 'cube' },
    { type: 'portal', x: 678, y: 0, portalType: 'speed_down' },

    // === SECTION 7: Transport + slopes finale (680-790) ===
    { type: 'checkpoint', x: 682, y: 0 },
    { type: 'spike', x: 690, y: 0 },
    { type: 'spike', x: 691, y: 0 },
    { type: 'transport', x: 696, y: 1, w: 3, h: 1, endX: 696, endY: 5, speed: 4 },
    { type: 'spike', x: 704, y: 0 },
    { type: 'spike', x: 705, y: 0 },
    { type: 'saw', x: 710, y: 2, radius: 1 },
    { type: 'spike', x: 716, y: 0 },
    { type: 'slope', x: 722, y: 0, w: 3, h: 2, direction: 'up' },
    { type: 'platform', x: 725, y: 2, w: 3, h: 1 },
    { type: 'spike', x: 726, y: 3 },
    { type: 'slope', x: 728, y: 2, w: 3, h: 2, direction: 'down' },
    { type: 'spike', x: 734, y: 0 },
    { type: 'spike', x: 735, y: 0 },
    { type: 'moving', x: 740, y: 1, w: 3, h: 1, endX: 740, endY: 4, speed: 4 },
    { type: 'spike', x: 746, y: 0 },
    { type: 'spike', x: 747, y: 0 },
    { type: 'saw', x: 752, y: 1, radius: 1 },
    { type: 'spike', x: 758, y: 0 },
    { type: 'orb', x: 764, y: 3, orbType: 'dash_orb' },
    { type: 'spike', x: 768, y: 0 },
    { type: 'spike', x: 769, y: 0 },
    { type: 'spike', x: 770, y: 0 },
    { type: 'coin', x: 776, y: 5 },
    { type: 'spike', x: 780, y: 0 },
    { type: 'spike', x: 781, y: 0 },
    { type: 'spike', x: 782, y: 0 },

    // === SECTION 8: Final gauntlet (790-860) ===
    { type: 'checkpoint', x: 792, y: 0 },
    { type: 'color_trigger', x: 794, y: 0, colorType: 'purple', duration: 0.4 },
    { type: 'spike', x: 800, y: 0 },
    { type: 'spike', x: 801, y: 0 },
    { type: 'spike', x: 802, y: 0 },
    { type: 'saw', x: 808, y: 1, radius: 1 },
    { type: 'orb', x: 814, y: 3, orbType: 'yellow_orb' },
    { type: 'spike', x: 816, y: 0 },
    { type: 'spike', x: 817, y: 0 },
    { type: 'spike', x: 818, y: 0 },
    { type: 'pad', x: 824, y: 0, padType: 'pink_pad' },
    { type: 'spike', x: 830, y: 0 },
    { type: 'spike', x: 831, y: 0 },
    { type: 'spike', x: 832, y: 0 },
    { type: 'saw', x: 838, y: 2, radius: 1.5 },
    { type: 'spike', x: 846, y: 0 },
    { type: 'spike', x: 847, y: 0 },
    { type: 'spike', x: 848, y: 0 },
    { type: 'spike', x: 849, y: 0 },
    { type: 'spike', x: 850, y: 0 },
    { type: 'spike', x: 851, y: 0 },
    { type: 'spike', x: 852, y: 0 },

    { type: 'end', x: 862 },
  ],
};
