/** Level 8 - Time Machine (Very Hard) ~90 seconds
 *  Features: complex transport combos, mini ship, gravity ship, all obstacles combined
 *  ~860 grid units */
export default {
  id: 8,
  name: 'Time Machine',
  speed: 1.0,
  objects: [
    // === SECTION 1: Brutal opening (0-100) ===
    { type: 'spike', x: 5, y: 0 },
    { type: 'spike', x: 6, y: 0 },
    { type: 'spike', x: 7, y: 0 },
    { type: 'saw', x: 12, y: 1, radius: 1 },
    { type: 'spike', x: 18, y: 0 },
    { type: 'spike', x: 19, y: 0 },
    { type: 'spike', x: 20, y: 0 },
    { type: 'orb', x: 24, y: 3, orbType: 'yellow_orb' },
    { type: 'spike', x: 26, y: 0 },
    { type: 'spike', x: 27, y: 0 },
    { type: 'spike', x: 28, y: 0 },
    { type: 'pad', x: 34, y: 0, padType: 'pink_pad' },
    { type: 'spike', x: 40, y: 0 },
    { type: 'spike', x: 41, y: 0 },
    { type: 'saw', x: 46, y: 2, radius: 1.5 },
    { type: 'spike', x: 54, y: 0 },
    { type: 'spike', x: 55, y: 0 },
    { type: 'spike', x: 56, y: 0 },
    { type: 'orb', x: 62, y: 2, orbType: 'dash_orb' },
    { type: 'spike', x: 66, y: 0 },
    { type: 'spike', x: 67, y: 0 },
    { type: 'slope', x: 72, y: 0, w: 2, h: 2, direction: 'up' },
    { type: 'platform', x: 74, y: 2, w: 3, h: 1 },
    { type: 'spike', x: 75, y: 3 },
    { type: 'slope', x: 77, y: 2, w: 2, h: 2, direction: 'down' },
    { type: 'spike', x: 82, y: 0 },
    { type: 'spike', x: 83, y: 0 },
    { type: 'spike', x: 88, y: 0 },
    { type: 'spike', x: 89, y: 0 },
    { type: 'spike', x: 90, y: 0 },
    { type: 'spike', x: 96, y: 0 },
    { type: 'spike', x: 97, y: 0 },

    // === SECTION 2: Transport chain (100-210) ===
    { type: 'checkpoint', x: 102, y: 0 },
    { type: 'color_trigger', x: 104, y: 0, colorType: 'yellow', duration: 0.8 },
    { type: 'spike', x: 110, y: 0 },
    { type: 'spike', x: 111, y: 0 },
    { type: 'transport', x: 116, y: 1, w: 3, h: 1, endX: 116, endY: 5, speed: 4 },
    { type: 'spike', x: 124, y: 0 },
    { type: 'saw', x: 130, y: 2, radius: 1 },
    { type: 'spike', x: 136, y: 0 },
    { type: 'spike', x: 137, y: 0 },
    { type: 'transport', x: 142, y: 1, w: 2, h: 1, endX: 142, endY: 4, speed: 3 },
    { type: 'spike', x: 148, y: 0 },
    { type: 'spike', x: 149, y: 0 },
    { type: 'spike', x: 150, y: 0 },
    { type: 'orb', x: 156, y: 3, orbType: 'pink_orb' },
    { type: 'spike', x: 158, y: 0 },
    { type: 'spike', x: 159, y: 0 },
    { type: 'coin', x: 164, y: 6 },
    { type: 'saw', x: 168, y: 1, radius: 1 },
    { type: 'spike', x: 174, y: 0 },
    { type: 'spike', x: 175, y: 0 },
    { type: 'moving', x: 180, y: 1, w: 3, h: 1, endX: 180, endY: 3, speed: 3 },
    { type: 'spike', x: 186, y: 0 },
    { type: 'spike', x: 187, y: 0 },
    { type: 'pad', x: 192, y: 0, padType: 'yellow_pad' },
    { type: 'spike', x: 196, y: 0 },
    { type: 'spike', x: 197, y: 0 },
    { type: 'spike', x: 198, y: 0 },
    { type: 'spike', x: 204, y: 0 },
    { type: 'spike', x: 205, y: 0 },

    // === SECTION 3: Mini ship corridor (210-340) ===
    { type: 'checkpoint', x: 212, y: 0 },
    { type: 'portal', x: 218, y: 0, portalType: 'mini' },
    { type: 'portal', x: 222, y: 0, portalType: 'ship' },
    { type: 'spike', x: 232, y: 0 },
    { type: 'spike', x: 232, y: 10, rot: 180 },
    { type: 'saw', x: 242, y: 5, radius: 1 },
    { type: 'spike', x: 250, y: 2 },
    { type: 'spike', x: 250, y: 8, rot: 180 },
    { type: 'spike', x: 258, y: 0 },
    { type: 'spike', x: 258, y: 10, rot: 180 },
    { type: 'saw', x: 268, y: 7, radius: 1 },
    { type: 'spike', x: 276, y: 1 },
    { type: 'spike', x: 276, y: 9, rot: 180 },
    { type: 'portal', x: 284, y: 0, portalType: 'gravity' },
    // Mini ship inverted
    { type: 'spike', x: 292, y: 0 },
    { type: 'spike', x: 292, y: 10, rot: 180 },
    { type: 'saw', x: 302, y: 4, radius: 1.5 },
    { type: 'spike', x: 310, y: 2 },
    { type: 'spike', x: 310, y: 9, rot: 180 },
    { type: 'portal', x: 318, y: 0, portalType: 'gravity' },
    { type: 'portal', x: 322, y: 0, portalType: 'big' },
    { type: 'portal', x: 326, y: 0, portalType: 'cube' },

    // === SECTION 4: Complex gravity (340-450) ===
    { type: 'checkpoint', x: 340, y: 0 },
    { type: 'color_trigger', x: 342, y: 0, colorType: 'orange', duration: 0.6 },
    { type: 'spike', x: 350, y: 0 },
    { type: 'spike', x: 351, y: 0 },
    { type: 'portal', x: 356, y: 0, portalType: 'gravity' },
    { type: 'spike', x: 362, y: 12, rot: 180 },
    { type: 'portal', x: 366, y: 0, portalType: 'gravity' },
    { type: 'spike', x: 372, y: 0 },
    { type: 'portal', x: 376, y: 0, portalType: 'gravity' },
    { type: 'spike', x: 382, y: 12, rot: 180 },
    { type: 'spike', x: 383, y: 12, rot: 180 },
    { type: 'portal', x: 388, y: 0, portalType: 'gravity' },
    { type: 'saw', x: 394, y: 1, radius: 1 },
    { type: 'spike', x: 400, y: 0 },
    { type: 'spike', x: 401, y: 0 },
    { type: 'orb', x: 406, y: 3, orbType: 'blue_orb' },
    { type: 'spike', x: 408, y: 12, rot: 180 },
    { type: 'spike', x: 409, y: 12, rot: 180 },
    { type: 'orb', x: 414, y: 9, orbType: 'yellow_orb' },
    { type: 'spike', x: 416, y: 12, rot: 180 },
    { type: 'spike', x: 417, y: 12, rot: 180 },
    { type: 'portal', x: 422, y: 0, portalType: 'gravity' },
    { type: 'spike', x: 428, y: 0 },
    { type: 'spike', x: 429, y: 0 },
    { type: 'spike', x: 430, y: 0 },
    { type: 'pad', x: 436, y: 0, padType: 'yellow_pad' },
    { type: 'spike', x: 440, y: 0 },
    { type: 'spike', x: 441, y: 0 },
    { type: 'spike', x: 442, y: 0 },

    // === SECTION 5: Wave + speed (450-560) ===
    { type: 'checkpoint', x: 452, y: 0 },
    { type: 'portal', x: 458, y: 0, portalType: 'speed_up' },
    { type: 'portal', x: 462, y: 0, portalType: 'wave' },
    { type: 'platform', x: 472, y: 3, w: 1, h: 9 },
    { type: 'platform', x: 480, y: 0, w: 1, h: 4 },
    { type: 'saw', x: 486, y: 7, radius: 1 },
    { type: 'platform', x: 492, y: 5, w: 1, h: 7 },
    { type: 'platform', x: 500, y: 0, w: 1, h: 5 },
    { type: 'saw', x: 506, y: 3, radius: 1 },
    { type: 'platform', x: 512, y: 4, w: 1, h: 8 },
    { type: 'platform', x: 520, y: 0, w: 1, h: 4 },
    { type: 'coin', x: 526, y: 6 },
    { type: 'platform', x: 532, y: 6, w: 1, h: 6 },
    { type: 'platform', x: 540, y: 0, w: 1, h: 5 },
    { type: 'portal', x: 548, y: 0, portalType: 'cube' },
    { type: 'portal', x: 550, y: 0, portalType: 'speed_down' },

    // === SECTION 6: Slope + saw assault (560-670) ===
    { type: 'checkpoint', x: 560, y: 0 },
    { type: 'spike', x: 568, y: 0 },
    { type: 'spike', x: 569, y: 0 },
    { type: 'slope', x: 574, y: 0, w: 3, h: 3, direction: 'up' },
    { type: 'platform', x: 577, y: 3, w: 3, h: 1 },
    { type: 'saw', x: 580, y: 5, radius: 1 },
    { type: 'slope', x: 580, y: 3, w: 3, h: 3, direction: 'down' },
    { type: 'spike', x: 586, y: 0 },
    { type: 'spike', x: 587, y: 0 },
    { type: 'saw', x: 592, y: 1, radius: 1 },
    { type: 'spike', x: 598, y: 0 },
    { type: 'orb', x: 604, y: 3, orbType: 'yellow_orb' },
    { type: 'spike', x: 606, y: 0 },
    { type: 'spike', x: 607, y: 0 },
    { type: 'slope', x: 612, y: 0, w: 2, h: 2, direction: 'up' },
    { type: 'platform', x: 614, y: 2, w: 2, h: 1 },
    { type: 'spike', x: 615, y: 3 },
    { type: 'slope', x: 616, y: 2, w: 2, h: 2, direction: 'down' },
    { type: 'spike', x: 622, y: 0 },
    { type: 'spike', x: 623, y: 0 },
    { type: 'spike', x: 624, y: 0 },
    { type: 'saw', x: 630, y: 2, radius: 1.5 },
    { type: 'spike', x: 638, y: 0 },
    { type: 'spike', x: 639, y: 0 },
    { type: 'pad', x: 644, y: 0, padType: 'pink_pad' },
    { type: 'spike', x: 650, y: 0 },
    { type: 'spike', x: 651, y: 0 },
    { type: 'spike', x: 652, y: 0 },
    { type: 'spike', x: 658, y: 0 },
    { type: 'spike', x: 659, y: 0 },
    { type: 'spike', x: 664, y: 0 },

    // === SECTION 7: Ball + gravity switches (670-780) ===
    { type: 'checkpoint', x: 672, y: 0 },
    { type: 'color_trigger', x: 674, y: 0, colorType: 'yellow', duration: 0.6 },
    { type: 'portal', x: 680, y: 0, portalType: 'ball' },
    { type: 'spike', x: 690, y: 0 },
    { type: 'platform', x: 694, y: 3, w: 5, h: 1 },
    { type: 'spike', x: 700, y: 0 },
    { type: 'spike', x: 701, y: 0 },
    { type: 'spike', x: 706, y: 0 },
    { type: 'platform', x: 710, y: 4, w: 4, h: 1 },
    { type: 'spike', x: 716, y: 0 },
    { type: 'spike', x: 717, y: 0 },
    { type: 'spike', x: 722, y: 0 },
    { type: 'spike', x: 723, y: 0 },
    { type: 'platform', x: 728, y: 3, w: 5, h: 1 },
    { type: 'spike', x: 736, y: 0 },
    { type: 'spike', x: 737, y: 0 },
    { type: 'spike', x: 742, y: 0 },
    { type: 'platform', x: 746, y: 4, w: 4, h: 1 },
    { type: 'spike', x: 752, y: 0 },
    { type: 'spike', x: 756, y: 0 },
    { type: 'spike', x: 757, y: 0 },
    { type: 'coin', x: 762, y: 5 },
    { type: 'spike', x: 766, y: 0 },
    { type: 'portal', x: 772, y: 0, portalType: 'cube' },

    // === SECTION 8: Final rush (780-860) ===
    { type: 'checkpoint', x: 782, y: 0 },
    { type: 'spike', x: 788, y: 0 },
    { type: 'spike', x: 789, y: 0 },
    { type: 'spike', x: 790, y: 0 },
    { type: 'saw', x: 796, y: 1, radius: 1 },
    { type: 'orb', x: 802, y: 3, orbType: 'yellow_orb' },
    { type: 'spike', x: 804, y: 0 },
    { type: 'spike', x: 805, y: 0 },
    { type: 'spike', x: 806, y: 0 },
    { type: 'pad', x: 812, y: 0, padType: 'pink_pad' },
    { type: 'spike', x: 818, y: 0 },
    { type: 'spike', x: 819, y: 0 },
    { type: 'spike', x: 820, y: 0 },
    { type: 'saw', x: 826, y: 2, radius: 1 },
    { type: 'orb', x: 832, y: 3, orbType: 'yellow_orb' },
    { type: 'spike', x: 834, y: 0 },
    { type: 'spike', x: 835, y: 0 },
    { type: 'spike', x: 836, y: 0 },
    { type: 'spike', x: 840, y: 0 },
    { type: 'spike', x: 841, y: 0 },
    { type: 'spike', x: 846, y: 0 },
    { type: 'spike', x: 847, y: 0 },
    { type: 'spike', x: 848, y: 0 },
    { type: 'spike', x: 852, y: 0 },
    { type: 'spike', x: 853, y: 0 },

    { type: 'end', x: 862 },
  ],
};
