/** Level 4 - Dry Out (Medium-Hard) ~90 seconds
 *  Introduces: slopes, saw blades, color triggers
 *  ~860 grid units */
export default {
  id: 4,
  name: 'Dry Out',
  speed: 1.0,
  objects: [
    // === SECTION 1: Slopes intro (0-110) ===
    { type: 'spike', x: 8, y: 0 },
    { type: 'spike', x: 9, y: 0 },
    { type: 'slope', x: 14, y: 0, w: 2, h: 1, direction: 'up' },
    { type: 'platform', x: 16, y: 1, w: 3, h: 1 },
    { type: 'spike', x: 17, y: 2 },
    { type: 'slope', x: 19, y: 1, w: 2, h: 1, direction: 'down' },
    { type: 'spike', x: 24, y: 0 },
    { type: 'spike', x: 25, y: 0 },
    { type: 'slope', x: 30, y: 0, w: 2, h: 2, direction: 'up' },
    { type: 'platform', x: 32, y: 2, w: 4, h: 1 },
    { type: 'spike', x: 34, y: 3 },
    { type: 'slope', x: 36, y: 2, w: 2, h: 2, direction: 'down' },
    { type: 'spike', x: 42, y: 0 },
    { type: 'spike', x: 43, y: 0 },
    { type: 'spike', x: 44, y: 0 },
    { type: 'orb', x: 50, y: 3, orbType: 'yellow_orb' },
    { type: 'spike', x: 52, y: 0 },
    { type: 'spike', x: 53, y: 0 },
    { type: 'slope', x: 58, y: 0, w: 3, h: 2, direction: 'up' },
    { type: 'platform', x: 61, y: 2, w: 2, h: 1 },
    { type: 'spike', x: 62, y: 3 },
    { type: 'spike', x: 66, y: 0 },
    { type: 'spike', x: 67, y: 0 },
    { type: 'pad', x: 72, y: 0, padType: 'yellow_pad' },
    { type: 'spike', x: 76, y: 0 },
    { type: 'spike', x: 77, y: 0 },
    { type: 'spike', x: 78, y: 0 },
    { type: 'orb', x: 84, y: 3, orbType: 'yellow_orb' },
    { type: 'spike', x: 86, y: 0 },
    { type: 'spike', x: 87, y: 0 },
    { type: 'spike', x: 92, y: 0 },
    { type: 'spike', x: 93, y: 0 },
    { type: 'spike', x: 100, y: 0 },
    { type: 'spike', x: 101, y: 0 },

    // === SECTION 2: Saw blade intro (110-220) ===
    { type: 'checkpoint', x: 110, y: 0 },
    { type: 'color_trigger', x: 112, y: 0, colorType: 'red', duration: 1.0 },
    { type: 'saw', x: 120, y: 1, radius: 1 },
    { type: 'spike', x: 126, y: 0 },
    { type: 'spike', x: 127, y: 0 },
    { type: 'saw', x: 134, y: 2, radius: 1 },
    { type: 'spike', x: 140, y: 0 },
    { type: 'slope', x: 144, y: 0, w: 2, h: 1, direction: 'up' },
    { type: 'platform', x: 146, y: 1, w: 3, h: 1 },
    { type: 'saw', x: 149, y: 3, radius: 1 },
    { type: 'slope', x: 149, y: 1, w: 2, h: 1, direction: 'down' },
    { type: 'spike', x: 154, y: 0 },
    { type: 'spike', x: 155, y: 0 },
    { type: 'orb', x: 160, y: 3, orbType: 'yellow_orb' },
    { type: 'spike', x: 162, y: 0 },
    { type: 'spike', x: 163, y: 0 },
    { type: 'coin', x: 168, y: 4 },
    { type: 'spike', x: 172, y: 0 },
    { type: 'spike', x: 173, y: 0 },
    { type: 'spike', x: 174, y: 0 },
    { type: 'saw', x: 180, y: 1, radius: 1.5 },
    { type: 'spike', x: 188, y: 0 },
    { type: 'spike', x: 189, y: 0 },
    { type: 'pad', x: 194, y: 0, padType: 'yellow_pad' },
    { type: 'spike', x: 198, y: 0 },
    { type: 'spike', x: 199, y: 0 },
    { type: 'orb', x: 206, y: 3, orbType: 'pink_orb' },
    { type: 'spike', x: 208, y: 0 },
    { type: 'spike', x: 209, y: 0 },
    { type: 'spike', x: 214, y: 0 },
    { type: 'spike', x: 215, y: 0 },

    // === SECTION 3: Ship with saws (220-350) ===
    { type: 'checkpoint', x: 222, y: 0 },
    { type: 'color_trigger', x: 224, y: 0, colorType: 'orange', duration: 0.8 },
    { type: 'portal', x: 232, y: 0, portalType: 'ship' },
    { type: 'spike', x: 242, y: 0 },
    { type: 'spike', x: 242, y: 10, rot: 180 },
    { type: 'saw', x: 252, y: 6, radius: 1.5 },
    { type: 'spike', x: 260, y: 2 },
    { type: 'spike', x: 260, y: 8, rot: 180 },
    { type: 'spike', x: 268, y: 0 },
    { type: 'spike', x: 268, y: 10, rot: 180 },
    { type: 'saw', x: 278, y: 5, radius: 1 },
    { type: 'spike', x: 286, y: 1 },
    { type: 'spike', x: 286, y: 9, rot: 180 },
    { type: 'spike', x: 294, y: 0 },
    { type: 'spike', x: 294, y: 10, rot: 180 },
    { type: 'saw', x: 304, y: 7, radius: 1 },
    { type: 'spike', x: 312, y: 2 },
    { type: 'spike', x: 312, y: 9, rot: 180 },
    { type: 'spike', x: 322, y: 0 },
    { type: 'spike', x: 322, y: 10, rot: 180 },
    { type: 'portal', x: 336, y: 0, portalType: 'cube' },

    // === SECTION 4: Gravity + saws (350-460) ===
    { type: 'checkpoint', x: 350, y: 0 },
    { type: 'spike', x: 358, y: 0 },
    { type: 'spike', x: 359, y: 0 },
    { type: 'saw', x: 366, y: 1, radius: 1 },
    { type: 'spike', x: 372, y: 0 },
    { type: 'portal', x: 378, y: 0, portalType: 'gravity' },
    { type: 'spike', x: 386, y: 12, rot: 180 },
    { type: 'spike', x: 387, y: 12, rot: 180 },
    { type: 'saw', x: 394, y: 10, radius: 1 },
    { type: 'spike', x: 400, y: 12, rot: 180 },
    { type: 'orb', x: 404, y: 9, orbType: 'yellow_orb' },
    { type: 'spike', x: 406, y: 12, rot: 180 },
    { type: 'spike', x: 407, y: 12, rot: 180 },
    { type: 'portal', x: 414, y: 0, portalType: 'gravity' },
    { type: 'spike', x: 420, y: 0 },
    { type: 'spike', x: 421, y: 0 },
    { type: 'coin', x: 428, y: 5 },
    { type: 'saw', x: 432, y: 2, radius: 1.5 },
    { type: 'spike', x: 438, y: 0 },
    { type: 'spike', x: 439, y: 0 },
    { type: 'pad', x: 444, y: 0, padType: 'yellow_pad' },
    { type: 'spike', x: 448, y: 0 },
    { type: 'spike', x: 449, y: 0 },
    { type: 'spike', x: 454, y: 0 },
    { type: 'spike', x: 455, y: 0 },

    // === SECTION 5: Slope gauntlet (460-570) ===
    { type: 'checkpoint', x: 462, y: 0 },
    { type: 'color_trigger', x: 464, y: 0, colorType: 'yellow', duration: 0.8 },
    { type: 'slope', x: 472, y: 0, w: 3, h: 2, direction: 'up' },
    { type: 'platform', x: 475, y: 2, w: 3, h: 1 },
    { type: 'spike', x: 477, y: 3 },
    { type: 'slope', x: 478, y: 2, w: 3, h: 2, direction: 'down' },
    { type: 'spike', x: 484, y: 0 },
    { type: 'spike', x: 485, y: 0 },
    { type: 'slope', x: 490, y: 0, w: 2, h: 2, direction: 'up' },
    { type: 'platform', x: 492, y: 2, w: 2, h: 1 },
    { type: 'slope', x: 494, y: 2, w: 2, h: 2, direction: 'up' },
    { type: 'platform', x: 496, y: 4, w: 3, h: 1 },
    { type: 'spike', x: 498, y: 5 },
    { type: 'slope', x: 499, y: 4, w: 2, h: 2, direction: 'down' },
    { type: 'spike', x: 504, y: 0 },
    { type: 'spike', x: 505, y: 0 },
    { type: 'orb', x: 512, y: 3, orbType: 'yellow_orb' },
    { type: 'spike', x: 514, y: 0 },
    { type: 'spike', x: 515, y: 0 },
    { type: 'saw', x: 520, y: 1, radius: 1 },
    { type: 'spike', x: 526, y: 0 },
    { type: 'slope', x: 532, y: 0, w: 3, h: 3, direction: 'up' },
    { type: 'platform', x: 535, y: 3, w: 3, h: 1 },
    { type: 'spike', x: 536, y: 4 },
    { type: 'slope', x: 538, y: 3, w: 3, h: 3, direction: 'down' },
    { type: 'spike', x: 544, y: 0 },
    { type: 'spike', x: 545, y: 0 },
    { type: 'pad', x: 550, y: 0, padType: 'pink_pad' },
    { type: 'spike', x: 556, y: 0 },
    { type: 'spike', x: 557, y: 0 },
    { type: 'spike', x: 562, y: 0 },
    { type: 'spike', x: 563, y: 0 },

    // === SECTION 6: Speed up + saws (570-680) ===
    { type: 'checkpoint', x: 572, y: 0 },
    { type: 'portal', x: 580, y: 0, portalType: 'speed_up' },
    { type: 'spike', x: 588, y: 0 },
    { type: 'saw', x: 594, y: 2, radius: 1 },
    { type: 'spike', x: 600, y: 0 },
    { type: 'spike', x: 601, y: 0 },
    { type: 'orb', x: 606, y: 3, orbType: 'yellow_orb' },
    { type: 'spike', x: 608, y: 0 },
    { type: 'spike', x: 609, y: 0 },
    { type: 'saw', x: 616, y: 1, radius: 1.5 },
    { type: 'spike', x: 624, y: 0 },
    { type: 'spike', x: 625, y: 0 },
    { type: 'pad', x: 630, y: 0, padType: 'yellow_pad' },
    { type: 'spike', x: 636, y: 0 },
    { type: 'spike', x: 637, y: 0 },
    { type: 'saw', x: 644, y: 2, radius: 1 },
    { type: 'spike', x: 650, y: 0 },
    { type: 'orb', x: 656, y: 3, orbType: 'pink_orb' },
    { type: 'spike', x: 658, y: 0 },
    { type: 'spike', x: 659, y: 0 },
    { type: 'spike', x: 664, y: 0 },
    { type: 'spike', x: 665, y: 0 },
    { type: 'portal', x: 674, y: 0, portalType: 'speed_down' },

    // === SECTION 7: Wave + saws (680-780) ===
    { type: 'checkpoint', x: 682, y: 0 },
    { type: 'color_trigger', x: 684, y: 0, colorType: 'orange', duration: 0.6 },
    { type: 'portal', x: 692, y: 0, portalType: 'wave' },
    { type: 'platform', x: 702, y: 4, w: 1, h: 8 },
    { type: 'platform', x: 712, y: 0, w: 1, h: 5 },
    { type: 'saw', x: 718, y: 7, radius: 1 },
    { type: 'platform', x: 724, y: 5, w: 1, h: 7 },
    { type: 'platform', x: 734, y: 0, w: 1, h: 4 },
    { type: 'saw', x: 740, y: 8, radius: 1 },
    { type: 'platform', x: 746, y: 6, w: 1, h: 6 },
    { type: 'platform', x: 756, y: 0, w: 1, h: 6 },
    { type: 'coin', x: 762, y: 6 },
    { type: 'portal', x: 770, y: 0, portalType: 'cube' },

    // === SECTION 8: Final rush (780-860) ===
    { type: 'checkpoint', x: 782, y: 0 },
    { type: 'spike', x: 790, y: 0 },
    { type: 'spike', x: 791, y: 0 },
    { type: 'spike', x: 792, y: 0 },
    { type: 'saw', x: 798, y: 1, radius: 1 },
    { type: 'orb', x: 804, y: 3, orbType: 'yellow_orb' },
    { type: 'spike', x: 806, y: 0 },
    { type: 'spike', x: 807, y: 0 },
    { type: 'spike', x: 808, y: 0 },
    { type: 'pad', x: 814, y: 0, padType: 'yellow_pad' },
    { type: 'spike', x: 818, y: 0 },
    { type: 'spike', x: 819, y: 0 },
    { type: 'spike', x: 820, y: 0 },
    { type: 'saw', x: 826, y: 2, radius: 1 },
    { type: 'spike', x: 832, y: 0 },
    { type: 'spike', x: 833, y: 0 },
    { type: 'spike', x: 834, y: 0 },
    { type: 'orb', x: 840, y: 3, orbType: 'yellow_orb' },
    { type: 'spike', x: 842, y: 0 },
    { type: 'spike', x: 843, y: 0 },
    { type: 'spike', x: 844, y: 0 },
    { type: 'spike', x: 850, y: 0 },
    { type: 'spike', x: 851, y: 0 },
    { type: 'spike', x: 852, y: 0 },

    { type: 'end', x: 862 },
  ],
};
